# Generated by Django 5.0.7 on 2024-12-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('desc', models.TextField(default='pending')),
            ],
        ),
        migrations.CreateModel(
            name='call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('desc', models.TextField(default='pending')),
                ('image', models.ImageField(default='pending', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('image', models.ImageField(default='pending', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('image', models.ImageField(default='pending', upload_to='images/')),
                ('desc', models.TextField(default='pending')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pending', upload_to='images/')),
                ('title', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('desc', models.TextField(default='pending')),
                ('image', models.ImageField(default='pending', upload_to='images/')),
            ],
        ),
    ]
