# Generated by Django 5.0.7 on 2024-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('image', models.ImageField(default='pending', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('title', models.CharField(default='pending', max_length=50)),
                ('rating', models.CharField(default='pending', max_length=50)),
                ('desc', models.TextField(default='pending')),
                ('image', models.ImageField(default='pending', upload_to='images/')),
            ],
        ),
    ]
