# Generated by Django 5.0.7 on 2024-12-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0002_team_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='desc1',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='about',
            name='desc2',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='about',
            name='desc3',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(default='pending', upload_to='images/'),
        ),
    ]
