# Generated by Django 5.0.7 on 2024-12-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0004_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logo',
            new_name='logos',
        ),
    ]
