# Generated by Django 5.0.7 on 2024-12-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0007_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.RemoveField(
            model_name='services',
            name='name',
        ),
    ]
