# Generated by Django 5.0.7 on 2024-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0008_remove_services_image_remove_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
