# Generated by Django 5.0.7 on 2024-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0009_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='call',
            old_name='name',
            new_name='button',
        ),
    ]
