# Generated by Django 5.0.7 on 2024-12-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0010_portfolio_rename_name_call_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
