# Generated by Django 5.0.7 on 2024-12-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0011_client_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
