# Generated by Django 5.0.7 on 2024-12-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0013_bgt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgt',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='filtered_images/'),
        ),
    ]
