# Generated by Django 5.0.7 on 2024-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0016_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_status',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
