# Generated by Django 5.0.7 on 2024-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0017_client_status_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('filtered_image', models.ImageField(blank=True, null=True, upload_to='filtered_images/')),
            ],
        ),
    ]
