# Generated by Django 5.0.7 on 2024-12-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0018_bgt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgt',
            name='filtered_image',
        ),
    ]
