# Generated by Django 5.0.7 on 2024-12-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0021_location_remove_testimony_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone',
        ),
    ]
