# Generated by Django 5.0.7 on 2024-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0023_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
