# Generated by Django 5.0.7 on 2024-12-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0025_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
