# Generated by Django 5.0.7 on 2024-12-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0026_product_qty_alter_product_price_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='desc2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='desc3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='label1',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='label2',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='label3',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
