# Generated by Django 5.0.7 on 2024-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0032_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='desc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='head',
            field=models.CharField(default='', max_length=50),
        ),
    ]
