# Generated by Django 5.0.7 on 2024-12-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0034_portfolio_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slide1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
