# Generated by Django 5.0.7 on 2024-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0038_field_header_indst_omesa_reside_delete_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='desc',
            field=models.TextField(),
        ),
    ]
