# Generated by Django 5.0.7 on 2024-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0039_alter_header_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indst',
            new_name='Indicate',
        ),
    ]
