# Generated by Django 5.0.7 on 2024-12-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0040_rename_indst_indicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='desc',
            field=models.TextField(),
        ),
    ]
