# Generated by Django 5.0.7 on 2024-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0041_alter_features_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
