# Generated by Django 5.0.7 on 2024-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umeme', '0042_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='name',
            field=models.CharField(default='image', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
